### ISSUE TITLE
2020年度总结 | Kotori

### ISSUE THREAD

**Issue by kotori-y** [kotori-y/blog_comment#23]
https://blog.iamkotori.com/2020/12/31/2020%E5%B9%B4%E5%BA%A6%E6%80%BB%E7%BB%93/

**Comment by IamCatkin** [comment]
gkdgkd

**Comment by kotori-y** [comment]
> @IamCatkin
> gkdgkd

在写了

**Comment by xiongguoli** [comment]
gkd

**Comment by IamCatkin** [comment]
gkdgkd

**Comment by xiongguoli** [comment]
我一个字也不配拥有，可以

**Comment by IamCatkin** [comment]
> @xiongguoli
> 我一个字也不配拥有，可以

确实，yzj太过分

**Comment by kotori-y** [comment]
> @xiongguoli
> 我一个字也不配拥有，可以

找机会给你安排上
